# Partner Queue Solution, which can be used completely for free.
# https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution
os: linux

arch:
  - arm64

# the default dist doesn't support grcov, so ubuntu 20.4 is used.
dist: focal

language: rust

env:
  global:
    # apps deployed here to avoid `sudo`
    - PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH

jobs:
  include:
    - rust: nightly
      env:
        # source-based coverage
        - RUSTFLAGS="-Cinstrument-coverage"
        - LLVM_PROFILE_FILE="coverage-%p-%m.profraw"

cache: cargo

before_install:
  - mkdir -p $HOME/.local/bin
  - mkdir -p $HOME/.cargo/bin

install:
  - rustup component add llvm-tools-preview
  - cargo install grcov

before_script: 

script:
  - cargo build --verbose
  - cargo test --all --verbose

after_success:
  - |
    if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      grcov . -s . --binary-path ./target/debug/ -t coveralls+ --llvm --branch --ignore-not-existing \
        --excl-start "#\[cfg\(test\)\]" \
        --excl-br-start "#\[cfg\(test\)\]" \
        --service-name travis-ci \
        --service-job-id $TRAVIS_JOB_ID \
        --service-pull-request $TRAVIS_PULL_REQUEST \
        --commit-sha $TRAVIS_COMMIT \
        --vcs-branch $TRAVIS_BRANCH \
        --token $COVERALLS_REPO_TOKEN > coveralls.json

      curl "https://coveralls.io/api/v1/jobs" -F json_file=@coveralls.json
    fi
