sudo: required # workaround for travis

language: rust

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - LOCAL="~/.local"  # install kcov here to avoid `sudo`
    - RUSTFLAGS='-C link-dead-code' # for code coverage analysis, because rustc strip dead code

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      #- libiberty-dev # <- no such thing in Ubuntu 12.04
      - g++

install:
    - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH
    - mkdir -p ~/.cargo/bin
    - mkdir -p ~/.local/bin

    # 1. Install kcov v34.
    - export KCOV_VERSION=34
    - |
        wget https://github.com/SimonKagstrom/kcov/archive/v${KCOV_VERSION}.tar.gz &&
        tar xzf v${KCOV_VERSION}.tar.gz &&
        cd kcov-${KCOV_VERSION} &&
        mkdir build &&
        cd build &&
        cmake .. &&
        make &&
        cp src/kcov src/libkcov_sowrapper.so ~/.cargo/bin &&
        cd ../..
    - kcov --version

    # 2. Install cargo-kcov.
    - cargo install cargo-kcov

after_success: |
  cargo kcov --verbose -- --verify --coveralls-id=$TRAVIS_JOB_ID \
    --strip-path=$TRAVIS_BUILD_DIR \
    --exclude-pattern=/.cargo,target \
    --exclude-region="#[cfg(test)]"