language: rust

cache: cargo

env:
  global:
    # install here to avoid `sudo`
    - PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH

jobs:
  include:
    - rust: nightly
      env: 
        - CARGO_INCREMENTAL=0
        - RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests"

addons:
  apt:
    packages:

install:
  - mkdir -p $HOME/.local/bin
  - mkdir -p $HOME/.cargo/bin

  - cargo install grcov

before_script: 

script:
  - cargo build --verbose
  - cargo test --all --verbose

after_success:
  - |
    if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      grcov . -s . -t coveralls+ --llvm --branch --ignore-not-existing \
        --excl-start "#\[cfg\(test\)\]" \
        --excl-br-start "#\[cfg\(test\)\]" \
        --service-name travis-ci \
        --service-job-id $TRAVIS_JOB_ID \
        --service-pull-request $TRAVIS_PULL_REQUEST \
        --commit-sha $TRAVIS_COMMIT \
        --vcs-branch $TRAVIS_BRANCH \
        --token $COVERALLS_REPO_TOKEN > coveralls.json

      curl "https://coveralls.io/api/v1/jobs" -F json_file=@coveralls.json
    fi
